#Requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0.0' }

<#
.SYNOPSIS
    Unit tests for ConvertFrom-SfvFile function.

.DESCRIPTION
    Tests SFV (Simple File Verification) file parsing.
    SFV files contain filename-to-CRC32 mappings used to verify file integrity.
#>

BeforeAll {
    Import-Module "$PSScriptRoot/../TestHelpers.psm1" -Force
    Initialize-TestEnvironment

    $script:tempDir = New-TestTempDirectory -Prefix 'SfvTest'
}

AfterAll {
    Remove-TestTempDirectory -Path $script:tempDir
}

Describe 'ConvertFrom-SfvFile' {

    Context 'Valid SFV file parsing' {
        It 'Parses single entry correctly' {
            $sfvPath = Join-Path $script:tempDir 'single.sfv'
            Set-Content -Path $sfvPath -Value 'testfile.rar 12345678'

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result.Count | Should -Be 1
                $result['testfile.rar'] | Should -Be 0x12345678
            }
        }

        It 'Parses multiple entries correctly' {
            $sfvPath = Join-Path $script:tempDir 'multiple.sfv'
            $content = @(
                'file1.rar AABBCCDD'
                'file2.r00 11223344'
                'file3.r01 DEADBEEF'
            )
            Set-Content -Path $sfvPath -Value $content

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result.Count | Should -Be 3
                $result['file1.rar'] | Should -Be 2864434397  # 0xAABBCCDD as uint32
                $result['file2.r00'] | Should -Be 287454020   # 0x11223344 as uint32
                $result['file3.r01'] | Should -Be 3735928559  # 0xDEADBEEF as uint32
            }
        }

        It 'Handles lowercase CRC values' {
            $sfvPath = Join-Path $script:tempDir 'lowercase.sfv'
            Set-Content -Path $sfvPath -Value 'test.rar abcdef12'

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result['test.rar'] | Should -Be 2882400018  # 0xABCDEF12 as uint32
            }
        }

        It 'Handles mixed case CRC values' {
            $sfvPath = Join-Path $script:tempDir 'mixedcase.sfv'
            Set-Content -Path $sfvPath -Value 'test.rar AbCdEf12'

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result['test.rar'] | Should -Be 2882400018  # 0xABCDEF12 as uint32
            }
        }

        It 'Handles filenames with spaces' {
            $sfvPath = Join-Path $script:tempDir 'spaces.sfv'
            Set-Content -Path $sfvPath -Value 'file with spaces.rar 12345678'

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result['file with spaces.rar'] | Should -Be 0x12345678
            }
        }
    }

    Context 'Comment and blank line handling' {
        It 'Skips comment lines starting with semicolon' {
            $sfvPath = Join-Path $script:tempDir 'comments.sfv'
            $content = @(
                '; This is a comment'
                'file.rar 12345678'
                '; Another comment'
            )
            Set-Content -Path $sfvPath -Value $content

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result.Count | Should -Be 1
                $result['file.rar'] | Should -Be 0x12345678
            }
        }

        It 'Skips blank lines' {
            $sfvPath = Join-Path $script:tempDir 'blanks.sfv'
            $content = @(
                ''
                'file.rar 12345678'
                ''
                '   '
            )
            Set-Content -Path $sfvPath -Value $content

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result.Count | Should -Be 1
            }
        }

        It 'Handles typical scene release SFV header' {
            $sfvPath = Join-Path $script:tempDir 'scene.sfv'
            $content = @(
                '; Generated by WIN-SFV32 v1.1a'
                ';'
                '; example.release-group'
                ';'
                'example.release-group.rar AABBCCDD'
                'example.release-group.r00 11223344'
            )
            Set-Content -Path $sfvPath -Value $content

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result.Count | Should -Be 2
            }
        }
    }

    Context 'Error handling' {
        It 'Throws on non-existent file' {
            InModuleScope 'ReScenePS' {
                { ConvertFrom-SfvFile -FilePath 'C:\nonexistent\fake.sfv' } | Should -Throw
            }
        }

        It 'Returns empty hashtable for empty file' {
            $sfvPath = Join-Path $script:tempDir 'empty.sfv'
            Set-Content -Path $sfvPath -Value ''

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result.Count | Should -Be 0
            }
        }

        It 'Ignores malformed lines' {
            $sfvPath = Join-Path $script:tempDir 'malformed.sfv'
            $content = @(
                'valid.rar 12345678'
                'invalid line without crc'
                'also-invalid'
                'another.rar AABBCCDD'
            )
            Set-Content -Path $sfvPath -Value $content

            InModuleScope 'ReScenePS' -Parameters @{ sfvPath = $sfvPath } {
                $result = ConvertFrom-SfvFile -FilePath $sfvPath
                $result.Count | Should -Be 2
                $result.ContainsKey('valid.rar') | Should -Be $true
                $result.ContainsKey('another.rar') | Should -Be $true
            }
        }
    }
}
